---
- name: install and start apache
  hosts: web
  become: yes # To activate privilege escalation.
  
  tasks:
    - name: httpd package is present
        yum:
          name: httpd
          state: latest
          
    - name: latest index.html file is present
      template:
          src: files/index.html
          dest: /var/www/html/
          
    - name:
      service:
          name: httpd
          state: started