---
- name: variable playbook test
  hosts: localhost
  
  tasks:
  - name: Ensure httpd package is present
    yum:
      name: httpd
      state: latest
    register: http_results
    
    
    # Using previous task state
  - name: Restart httpd
    service:
      name: httpd
      state: restart
    when: http_results.changed