---
- name: variable playbook test
  hosts: localhost
  
  tasks:
  - name: Ensure httpd package is present
    yum:
      name: httpd
      state: latest
    notify: restart_httpd
    
    
  # Handler Tasks -> If either task notifies a changed result, the handler will be notified once. 
  handlers:
  - name: restart_httpd
    service:
      name: httpd
      state: restart
    