---
- name: Install NGINX Plus
  hosts: all
  tasks:
    - name: Install NGINX
      include_role:
        name: nginxinc.nginx
      vars:
        nginx_type: plus

    - name: Install NGINX App Protect
      include_role:
        name: nginxinc.nginx_app_protect
      vars:
        nginx_app_protect_setup_license: false
        nginx_app_protect_remove_license: false
        nginx_app_protect_install_signatures: false
        
        
# nginx_core
# |-- MANIFEST.json
# |-- playbooks
# |     |-- deploy-nginx.yml
# |     |--
# |-- plugins
# |-- README.md
# |-- roles
#      |-- nginx
#      |    |-- defaults
#      |    |-- files
#      |    |-- ...
#      |-- nginx_app_protect
#      |-- nginx_config